//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Code { get; set; }
        public Nullable<int> DescriberUserCode { get; set; }
        public Nullable<int> DescriptedUserCode { get; set; }
        public string Feedback1 { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
