//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingSpotSearch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParkingSpotSearch()
        {
            this.SearchResults = new HashSet<SearchResult>();
        }
    
        public int Code { get; set; }
        public Nullable<int> UserId { get; set; }
        public string MyLocationAddress { get; set; }
        public string Place_id { get; set; }
        public Nullable<int> CityCode { get; set; }
        public Nullable<bool> SizeOpt { get; set; }
        public Nullable<double> PreferableWidth { get; set; }
        public Nullable<double> PreferableLength { get; set; }
        public Nullable<bool> RoofOpt { get; set; }
        public Nullable<int> DaysSchedule { get; set; }
        public Nullable<double> MinPrice { get; set; }
        public Nullable<double> MaxPrice { get; set; }
        public Nullable<bool> Regularly { get; set; }
        public Nullable<System.DateTime> SearchDate { get; set; }
    
        public virtual City City { get; set; }
        public virtual WeekDay WeekDay { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchResult> SearchResults { get; set; }
    }
}
