//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchResult
    {
        public int Code { get; set; }
        public Nullable<int> Usercode { get; set; }
        public Nullable<int> SearchCode { get; set; }
        public Nullable<int> ResultPSCode { get; set; }
    
        public virtual ParkingSpot ParkingSpot { get; set; }
        public virtual ParkingSpotSearch ParkingSpotSearch { get; set; }
        public virtual User User { get; set; }
    }
}
