//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekDay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeekDay()
        {
            this.ParkingSpots = new HashSet<ParkingSpot>();
            this.ParkingSpotSearches = new HashSet<ParkingSpotSearch>();
        }
    
        public int Code { get; set; }
        public Nullable<long> Sunday1HourQuaters { get; set; }
        public Nullable<long> Sunday2HourQuaters { get; set; }
        public Nullable<long> Monday1HourQuaters { get; set; }
        public Nullable<long> Monday2HourQuaters { get; set; }
        public Nullable<long> Tueday1HourQuaters { get; set; }
        public Nullable<long> Tueday2HourQuaters { get; set; }
        public Nullable<long> Wednesday1HourQuaters { get; set; }
        public Nullable<long> Wednesday2HourQuaters { get; set; }
        public Nullable<long> Thursday1HourQuaters { get; set; }
        public Nullable<long> Thursday2HourQuaters { get; set; }
        public Nullable<long> Friday1HourQuaters { get; set; }
        public Nullable<long> Friday2HourQuaters { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParkingSpot> ParkingSpots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParkingSpotSearch> ParkingSpotSearches { get; set; }
    }
}
